-- MySQL Script generated by MySQL Workbench
-- vie 11 sep 2020 18:05:10 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kdbot_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kdbot_dev` ;

-- -----------------------------------------------------
-- Schema kdbot_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kdbot_dev` DEFAULT CHARACTER SET utf8mb4 ;
-- -----------------------------------------------------
-- Schema kdbot_dev
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `kdbot_dev` ;

-- -----------------------------------------------------
-- Schema kdbot_dev
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kdbot_dev` DEFAULT CHARACTER SET utf8mb4 ;
USE `kdbot_dev` ;
USE `kdbot_dev` ;

-- -----------------------------------------------------
-- Table `kdbot_dev`.`groups_companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`groups_companies` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`groups_companies` (
  `idgroup_company` INT NOT NULL,
  `group_name` VARCHAR(45) NULL,
  `group_admin_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idgroup_company`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`companies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`companies` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`companies` (
  `idcompany` INT NOT NULL,
  `company_name` VARCHAR(45) NULL,
  `tax_identification` VARCHAR(45) NULL,
  `registry_number` VARCHAR(45) NULL,
  `phone` VARCHAR(15) NULL,
  `company_creator_id` INT NOT NULL,
  `idgroup_companies` INT NOT NULL,
  `company_code` VARCHAR(5) NULL,
  `woo_ck` VARCHAR(50) NULL,
  `woo_cs` VARCHAR(50) NULL,
  `ecommerce_url` VARCHAR(150) NULL,
  PRIMARY KEY (`idcompany`, `company_creator_id`, `idgroup_companies`),
  INDEX `fk_companies_companies1_idx` (`company_creator_id` ASC),
  INDEX `fk_companies_groups_companies1_idx` (`idgroup_companies` ASC),
  CONSTRAINT `fk_companies_companies1`
    FOREIGN KEY (`company_creator_id`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_companies_groups_companies1`
    FOREIGN KEY (`idgroup_companies`)
    REFERENCES `kdbot_dev`.`groups_companies` (`idgroup_company`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`categories` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`categories` (
  `idcategory` INT(11) NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NULL DEFAULT NULL,
  `category_description` VARCHAR(150) NULL,
  `category_img` VARCHAR(150) NULL,
  `category_type` INT(2) NULL DEFAULT NULL,
  `category_status` INT NULL,
  `companies_idcompanies` INT NOT NULL,
  `category_idcategory` INT(11) NOT NULL,
  PRIMARY KEY (`idcategory`, `companies_idcompanies`, `category_idcategory`),
  INDEX `fk_category_companies1_idx` (`companies_idcompanies` ASC),
  INDEX `fk_category_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_category_companies1`
    FOREIGN KEY (`companies_idcompanies`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `kdbot_dev`.`categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`intents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`intents` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`intents` (
  `idintent` INT(11) NOT NULL AUTO_INCREMENT,
  `intent_name` VARCHAR(65) NULL DEFAULT NULL,
  `training_phrases` VARCHAR(500) NULL DEFAULT NULL,
  `companies_idcompanies` INT NOT NULL,
  PRIMARY KEY (`idintent`, `companies_idcompanies`),
  INDEX `fk_intents_companies1_idx` (`companies_idcompanies` ASC),
  CONSTRAINT `fk_intents_companies1`
    FOREIGN KEY (`companies_idcompanies`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`products` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`products` (
  `idproduct` INT(11) NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL DEFAULT NULL,
  `product_description` VARCHAR(300) NULL DEFAULT NULL,
  `product_short_description` VARCHAR(70) NULL,
  `product_price` FLOAT(5,2) NULL DEFAULT NULL,
  `product_stock` INT(11) NULL DEFAULT NULL,
  `product_status` VARCHAR(15) NULL DEFAULT NULL,
  `product_img` VARCHAR(150) NULL DEFAULT NULL,
  `limit_products_order` INT(11) NULL DEFAULT NULL,
  `category_idcategory` INT(11) NOT NULL,
  PRIMARY KEY (`idproduct`, `category_idcategory`),
  INDEX `fk_products_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `kdbot_dev`.`categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`intents_responses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`intents_responses` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`intents_responses` (
  `idresponse` INT(11) NOT NULL AUTO_INCREMENT,
  `response_text` VARCHAR(500) NULL DEFAULT NULL,
  `img_url` VARCHAR(150) NULL,
  `response_title` VARCHAR(150) NULL,
  `response_link` VARCHAR(150) NULL,
  `response_source` VARCHAR(15) NULL DEFAULT NULL,
  `response_type` VARCHAR(45) NULL DEFAULT NULL,
  `intents_idintent` INT(11) NOT NULL,
  PRIMARY KEY (`idresponse`, `intents_idintent`),
  INDEX `fk_responses_intents1_idx` (`intents_idintent` ASC),
  CONSTRAINT `fk_responses_intents1`
    FOREIGN KEY (`intents_idintent`)
    REFERENCES `kdbot_dev`.`intents` (`idintent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`services` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`services` (
  `id_service` INT NOT NULL,
  `service_name` VARCHAR(45) NULL,
  `service_description` VARCHAR(200) NULL,
  `service_price` FLOAT(5,2) NULL,
  `category_idcategory` INT(11) NOT NULL,
  `service_duration_time` VARCHAR(45) NULL,
  `concurrent_services` INT NULL,
  PRIMARY KEY (`id_service`, `category_idcategory`),
  INDEX `fk_Services_category1_idx` (`category_idcategory` ASC),
  CONSTRAINT `fk_Services_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `kdbot_dev`.`categories` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`customers` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`customers` (
  `idcustomer` INT NOT NULL AUTO_INCREMENT,
  `customer_name` VARCHAR(45) NULL,
  `customer_last_name` VARCHAR(45) NULL,
  `customer_phone` VARCHAR(15) NULL,
  `customer_email` VARCHAR(45) NULL,
  `customer_birthday` DATE NULL,
  `gender` VARCHAR(45) NULL,
  `dni` VARCHAR(45) NULL,
  `tax_id` VARCHAR(45) NULL,
  `customer_status` VARCHAR(15) NULL,
  `companies_idcompany` INT NOT NULL,
  `fb_user_id` VARCHAR(45) NULL,
  PRIMARY KEY (`idcustomer`, `companies_idcompany`),
  INDEX `fk_customers_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_customers_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`orders` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`orders` (
  `idorder` INT NOT NULL AUTO_INCREMENT,
  `order_status` INT NULL,
  `order_date_time` TIMESTAMP NULL,
  `local_date_time` TIMESTAMP NULL,
  `dispatch_time` TIMESTAMP NULL,
  `customer_idcustomer` INT NOT NULL,
  `id_customer_address` INT NULL,
  `id_branch_office` INT NULL,
  `delivery_type` VARCHAR(45) NULL,
  `method_of_payment` VARCHAR(45) NULL,
  `total` FLOAT(6,2) NULL,
  `others_details` VARCHAR(500) NULL,
  PRIMARY KEY (`idorder`, `customer_idcustomer`),
  INDEX `fk_orders_Customer1_idx` (`customer_idcustomer` ASC),
  CONSTRAINT `fk_orders_Customer1`
    FOREIGN KEY (`customer_idcustomer`)
    REFERENCES `kdbot_dev`.`customers` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`reservations` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`reservations` (
  `idreservation` INT NOT NULL,
  `reservation_status` VARCHAR(15) NULL,
  `reservation_start_date` TIMESTAMP NULL,
  `reservation_end_time` TIMESTAMP NULL,
  `Customer_idCustomer` INT NOT NULL,
  `reservation_total_price` FLOAT(3,2) NULL,
  PRIMARY KEY (`idreservation`, `Customer_idCustomer`),
  INDEX `fk_reservations_Customer1_idx` (`Customer_idCustomer` ASC),
  CONSTRAINT `fk_reservations_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `kdbot_dev`.`customers` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`reservations_has_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`reservations_has_services` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`reservations_has_services` (
  `reservations_idreservations` INT NOT NULL,
  `services_id_services` INT NOT NULL,
  PRIMARY KEY (`reservations_idreservations`, `services_id_services`),
  INDEX `fk_reservations_has_services_services1_idx` (`services_id_services` ASC),
  INDEX `fk_reservations_has_services_reservations1_idx` (`reservations_idreservations` ASC),
  CONSTRAINT `fk_reservations_has_services_reservations1`
    FOREIGN KEY (`reservations_idreservations`)
    REFERENCES `kdbot_dev`.`reservations` (`idreservation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservations_has_services_services1`
    FOREIGN KEY (`services_id_services`)
    REFERENCES `kdbot_dev`.`services` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`adresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`adresses` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`adresses` (
  `idadress` INT NOT NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `address` VARCHAR(200) NULL,
  `adresse_reference` VARCHAR(200) NULL,
  `postal_code` VARCHAR(45) NULL,
  `priority` TINYINT(4) NULL,
  `Customer_idCustomer` INT NOT NULL,
  `address_long` VARCHAR(45) NULL,
  `adress_lat` VARCHAR(45) NULL,
  PRIMARY KEY (`idadress`, `Customer_idCustomer`),
  INDEX `fk_adresses_Customer1_idx` (`Customer_idCustomer` ASC),
  CONSTRAINT `fk_adresses_Customer1`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `kdbot_dev`.`customers` (`idcustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`options` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`options` (
  `idoption` INT NOT NULL,
  `option_var` VARCHAR(45) NULL,
  `option_value` VARCHAR(45) NULL,
  `option_description` VARCHAR(45) NULL,
  `companies_idcompany` INT NOT NULL,
  PRIMARY KEY (`idoption`, `companies_idcompany`),
  INDEX `fk_options_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_options_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`bitacora` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`bitacora` (
  `idbitacora` INT NOT NULL,
  `operation` VARCHAR(45) NULL,
  `id_user` VARCHAR(45) NULL,
  `date` TIMESTAMP NULL,
  `query` VARCHAR(800) NULL,
  PRIMARY KEY (`idbitacora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`branch_offices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`branch_offices` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`branch_offices` (
  `idbranch_office` INT NOT NULL,
  `office_name` VARCHAR(45) NULL,
  `office_address` VARCHAR(200) NULL,
  `office_phone` VARCHAR(45) NULL,
  `principal` INT NULL,
  `companies_idcompany` INT NOT NULL,
  `long` VARCHAR(45) NULL,
  `lat` VARCHAR(45) NULL,
  `google_maps_url` VARCHAR(150) NULL,
  `office_capacity_service` INT NULL,
  `office_hours` VARCHAR(150) NULL,
  `fb_page_id` VARCHAR(45) NULL,
  `agent_id` VARCHAR(45) NULL,
  `telegram_chanel` VARCHAR(45) NULL,
  `telegram_token` VARCHAR(65) NULL,
  PRIMARY KEY (`idbranch_office`, `companies_idcompany`),
  INDEX `fk_branch_office_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_branch_office_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`roles` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`roles` (
  `idrole` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL,
  `role_description` VARCHAR(200) NULL,
  `permissions` VARCHAR(500) NULL,
  PRIMARY KEY (`idrole`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`users` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`users` (
  `iduser` INT NOT NULL,
  `user_name` VARCHAR(45) NULL,
  `user_lastname` VARCHAR(45) NULL,
  `user_position` VARCHAR(45) NULL,
  `user_phone` VARCHAR(15) NULL,
  `user_custom_id` VARCHAR(10) NULL,
  `user_email` VARCHAR(45) NULL,
  `user_nickname` VARCHAR(15) NULL,
  `user_pass` VARCHAR(45) NULL,
  `user_birtday` DATE NULL,
  `user_last_sesion` TIMESTAMP NULL,
  `user_creation_date` TIMESTAMP NULL,
  `user_status` VARCHAR(15) NULL,
  `user_end_date` TIMESTAMP NULL,
  `creator_id` INT NULL,
  `latest_data_update` TIMESTAMP NULL,
  `role_idrole` INT NOT NULL,
  `companies_idcompany` INT NOT NULL,
  PRIMARY KEY (`iduser`, `role_idrole`, `companies_idcompany`),
  INDEX `fk_user_role1_idx` (`role_idrole` ASC),
  INDEX `fk_user_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_user_role1`
    FOREIGN KEY (`role_idrole`)
    REFERENCES `kdbot_dev`.`roles` (`idrole`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = cp850;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`contracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`contracts` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`contracts` (
  `idcontract` INT NOT NULL,
  `contract_name` VARCHAR(45) NULL,
  `contract_start_date` DATE NULL,
  `contract_end_date` DATE NULL,
  `contract_status` VARCHAR(45) NULL,
  `companies_idcompany` INT NOT NULL,
  PRIMARY KEY (`idcontract`, `companies_idcompany`),
  INDEX `fk_contracts_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_contracts_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`products_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`products_services` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`products_services` (
  `idproducts_services` INT NOT NULL,
  `ps_name` VARCHAR(45) NULL,
  `ps_description` VARCHAR(200) NULL,
  `precio` FLOAT(5,2) NULL,
  PRIMARY KEY (`idproducts_services`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`contracts_has_products_services`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`contracts_has_products_services` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`contracts_has_products_services` (
  `contracts_idcontracts` INT NOT NULL,
  `products_services_idproducts_services` INT NOT NULL,
  PRIMARY KEY (`contracts_idcontracts`, `products_services_idproducts_services`),
  INDEX `fk_contracts_has_products_services_products_services1_idx` (`products_services_idproducts_services` ASC),
  INDEX `fk_contracts_has_products_services_contracts1_idx` (`contracts_idcontracts` ASC),
  CONSTRAINT `fk_contracts_has_products_services_contracts1`
    FOREIGN KEY (`contracts_idcontracts`)
    REFERENCES `kdbot_dev`.`contracts` (`idcontract`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contracts_has_products_services_products_services1`
    FOREIGN KEY (`products_services_idproducts_services`)
    REFERENCES `kdbot_dev`.`products_services` (`idproducts_services`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`invoices` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`invoices` (
  `idinvoices` INT NOT NULL,
  `invoice_start_date` VARCHAR(45) NULL,
  `invoice_end_date` VARCHAR(45) NULL,
  `invoice_details` VARCHAR(45) NULL,
  `invoice_status` VARCHAR(45) NULL,
  `invoice_creation_date` VARCHAR(45) NULL,
  `invoice_amount` VARCHAR(45) NULL,
  `invoice_discounts` VARCHAR(45) NULL,
  `invoice_total` FLOAT(5,2) NULL,
  `companies_idcompanies` INT NOT NULL,
  PRIMARY KEY (`idinvoices`, `companies_idcompanies`),
  INDEX `fk_invoices_companies1_idx` (`companies_idcompanies` ASC),
  CONSTRAINT `fk_invoices_companies1`
    FOREIGN KEY (`companies_idcompanies`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`contexts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`contexts` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`contexts` (
  `idcontext` INT NOT NULL,
  `context_name` VARCHAR(45) NULL,
  `companies_idcompany` INT NOT NULL,
  PRIMARY KEY (`idcontext`, `companies_idcompany`),
  INDEX `fk_contexts_companies1_idx` (`companies_idcompany` ASC),
  CONSTRAINT `fk_contexts_companies1`
    FOREIGN KEY (`companies_idcompany`)
    REFERENCES `kdbot_dev`.`companies` (`idcompany`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`intents_has_contexts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`intents_has_contexts` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`intents_has_contexts` (
  `intents_idintent` INT(11) NOT NULL,
  `contexts_idcontext` INT NOT NULL,
  `context_type` VARCHAR(5) NULL,
  `context_lifespan` INT NULL,
  PRIMARY KEY (`intents_idintent`, `contexts_idcontext`),
  INDEX `fk_intents_has_contexts_contexts1_idx` (`contexts_idcontext` ASC),
  INDEX `fk_intents_has_contexts_intents1_idx` (`intents_idintent` ASC),
  CONSTRAINT `fk_intents_has_contexts_intents1`
    FOREIGN KEY (`intents_idintent`)
    REFERENCES `kdbot_dev`.`intents` (`idintent`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_intents_has_contexts_contexts1`
    FOREIGN KEY (`contexts_idcontext`)
    REFERENCES `kdbot_dev`.`contexts` (`idcontext`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`orders_has_products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`orders_has_products` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`orders_has_products` (
  `orders_idorder` INT NOT NULL,
  `products_idproducts` INT(11) NOT NULL,
  `op_quantity` INT NULL,
  `op_price` FLOAT(6,2) NULL,
  `op_subtotal` FLOAT(6,2) NULL,
  PRIMARY KEY (`orders_idorder`, `products_idproducts`),
  INDEX `fk_orders_has_products_products1_idx` (`products_idproducts` ASC),
  INDEX `fk_orders_has_products_orders1_idx` (`orders_idorder` ASC),
  CONSTRAINT `fk_orders_has_products_orders1`
    FOREIGN KEY (`orders_idorder`)
    REFERENCES `kdbot_dev`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_products_products1`
    FOREIGN KEY (`products_idproducts`)
    REFERENCES `kdbot_dev`.`products` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`calendar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`calendar` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`calendar` (
  `idcalendar` INT NOT NULL,
  `date` TIMESTAMP NULL,
  PRIMARY KEY (`idcalendar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kdbot_dev`.`service_available`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kdbot_dev`.`service_available` ;

CREATE TABLE IF NOT EXISTS `kdbot_dev`.`service_available` (
  `offices_idbranch_office` INT NOT NULL,
  `calendar_idcalendar` INT NOT NULL,
  `services_id_service` INT NOT NULL,
  `service_available` INT NULL,
  `scheduled_services` INT NULL,
  `comment` VARCHAR(45) NULL,
  PRIMARY KEY (`offices_idbranch_office`, `calendar_idcalendar`, `services_id_service`),
  INDEX `fk_branch_offices_has_calendar_calendar1_idx` (`calendar_idcalendar` ASC),
  INDEX `fk_branch_offices_has_calendar_branch_offices1_idx` (`offices_idbranch_office` ASC),
  INDEX `fk_service_available_services1_idx` (`services_id_service` ASC),
  CONSTRAINT `fk_branch_offices_has_calendar_branch_offices1`
    FOREIGN KEY (`offices_idbranch_office`)
    REFERENCES `kdbot_dev`.`branch_offices` (`idbranch_office`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_branch_offices_has_calendar_calendar1`
    FOREIGN KEY (`calendar_idcalendar`)
    REFERENCES `kdbot_dev`.`calendar` (`idcalendar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_service_available_services1`
    FOREIGN KEY (`services_id_service`)
    REFERENCES `kdbot_dev`.`services` (`id_service`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
